# Generated by Django 4.2.7 on 2026-08-28 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incident_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incidentstatushistory",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="incidents.incident",
            ),
        ),
        migrations.AddField(
            model_name="incidentmedia",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="incidents.incident",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["user", "-created_at"], name="incidents_i_user_id_f06592_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["status", "-created_at"], name="incidents_i_status_3b7181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["type"], name="incidents_i_type_2c1cd5_idx"),
        ),
    ]
