# Generated by Django 4.2.7 on 2026-08-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidentstatushistory",
            options={"ordering": ("-sequence", "-changed_at")},
        ),
        migrations.AddField(
            model_name="incidentstatushistory",
            name="sequence",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
