# Generated by Django 4.2.7 on 2026-09-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidentmedia",
            options={"ordering": ("-uploaded_at",)},
        ),
        migrations.AlterField(
            model_name="incident",
            name="location_lat",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="incident",
            name="location_lng",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="incident",
            name="type",
            field=models.CharField(
                choices=[("accident", "Accident"), ("emergency", "Emergency")],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="incidentmedia",
            name="media_url",
            field=models.URLField(max_length=500),
        ),
        migrations.AddIndex(
            model_name="incidentmedia",
            index=models.Index(
                fields=["incident"], name="incidents_i_inciden_e62eb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentmedia",
            index=models.Index(
                fields=["media_type"], name="incidents_i_media_t_78eb39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentstatushistory",
            index=models.Index(
                fields=["incident"], name="incidents_i_inciden_c7041b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentstatushistory",
            index=models.Index(
                fields=["-sequence", "-changed_at"],
                name="incidents_i_sequenc_848853_idx",
            ),
        ),
    ]
